compat: sqlalchemy 2+ case() requires whens= as args, not a list
Per error:
sqlalchemy.exc.ArgumentError: The "whens" argument to case(), when
referring to a sequence of items, is now passed as a series of
positional elements, rather than as a list.